workflows:
  android-workflow:
    name: Android Workflow
    instance_type: mac_mini_m1
    max_build_duration: 120
    triggering:
       events:
         - push
       branch_patterns:
         - pattern: 'main'
           include: true
           source: true 
    environment:
      android_signing:
        - noting_reference
      groups:
        - google_play 
      vars:
        PACKAGE_NAME: "$CM_PACKAGE_NAME" 
        GCLOUD_SERVICE_ACCOUNT_CREDENTIALS: "$CM_GCLOUD_SERVICE_ACCOUNT_CREDENTIALS"
      flutter: "3.10.6"
    scripts:
      - name: Debugging
        script: |
          echo "PACKAGE_NAME: $CM_PACKAGE_NAME"
          echo "GCLOUD_SERVICE_ACCOUNT_CREDENTIALS: $CM_GCLOUD_SERVICE_ACCOUNT_CREDENTIALS"
          echo "flutter.sdk: $HOME/programs/flutter"
          echo "CM_BUILD_DIR: $CM_BUILD_DIR"
          MAJOR_VERSION="3.0"
          BUILD_NUMBER=$(($(google-play get-latest-build-number --package-name "$CM_PACKAGE_NAME" --tracks=production --credentials="$CM_GCLOUD_SERVICE_ACCOUNT_CREDENTIALS") + 1))      
          echo "Calculated BUILD_NUMBER: $BUILD_NUMBER"
          echo "MAJOR_VERSION: $MAJOR_VERSION"

      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Flutter analyze
        script: |
          flutter analyze
      - name: Flutter unit tests
        script: |
          flutter test
        ignore_failure: true
      - name: Build AAB with Flutter
        script: |
          MAJOR_VERSION="4.0"
          BUILD_NUMBER=$(($(google-play get-latest-build-number --package-name "$CM_PACKAGE_NAME" --tracks=production --credentials="$CM_GCLOUD_SERVICE_ACCOUNT_CREDENTIALS") + 1))      
          echo "Calculated BUILD_NUMBER: $BUILD_NUMBER"
          flutter build appbundle --release \
            --build-name=$MAJOR_VERSION.$BUILD_NUMBER \
            --build-number=$BUILD_NUMBER
    artifacts:
      - build/**/outputs/**/*.aab
      - build/**/outputs/**/mapping.txt
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - zeeshansheikh921837@gmail.com
        notify:
          success: true
          failure: false
      google_play:
        credentials: $CM_GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: production

